version: '3'
services:
  
  database:
    ports:
      - 5432:5432
    volumes:
      - ./hvz-data-test/:/var/lib/postgresql/data/

  selenium_grid:
    image: selenium/standalone-firefox
    container_name: hvz_test
    depends_on:
      - web
    ports:
      - 4444:4444

  e2etests:
    build:
      context: .
      dockerfile: ./config/e2etests/Dockerfile
    container_name: hvz_e2etests
    environment: 
      DB_HOST: database
      SELENIUM_HOST: hvz_test
      WEB_HOST: hvz_web
    depends_on:
      - database
      - api
      - web
      - selenium_grid
    volumes:
      - ./frontend/test_e2e/:/code/test_e2e/
      - ./frontend/:/frontend/
    command:       
      - /bin/sh
      - -c
      - |
        cp /frontend/pytest.ini /code
        cd code
        pytest -v | tee /frontend/pytest-results-$$(date +%Y-%m-%d-%H-%M-%S).txt

    
    