version: '3'
services:
  web:
    image: nginx:latest
    container_name: hvz_web
    depends_on:
      - flask
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/:/www/
    ports:
      - 80:80
      - 443:443

  flask:
    build: ./config/flask
    container_name: hvz_flask
    depends_on:
      - database
    volumes:
      - ./backend/:/code/
    environment:
      FLASK_ENV: development
      TEST: test

  database:
    image: postgres:latest
    container_name: hvz_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test
