version: '3'
services:
  
  selenium:
    image: selenium/standalone-chrome
    container_name: hvz_selenium
    shm_size: '2gb' 
    depends_on:
      - web

  e2etests:
    build:
      context: ./config/e2etests
    container_name: hvz_e2etests
    depends_on:
      - selenium
    volumes:
      - ./e2etests/:/code/

