version: "3"
services:
  web:
    build:
      context: .
      dockerfile: ./config/web-server/Dockerfile

    container_name: hvz_web
    depends_on:
      - api
    ports:
      - 80:80
      - 443:443

  api:
    build:
      context: .
      dockerfile: ./config/api/Dockerfile
      args:
        SPECIAL_REQUIREMENTS: "production-requirements.txt"

    container_name: hvz_api
    entrypoint: ["uwsgi", "--ini", "app.ini"]
    depends_on:
      - database
    environment:
      DATABASE: hvz_production

  database:
    image: postgres:latest
    container_name: hvz_db
    volumes:
      - ./hvz-data/:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: hvz_production
