version: '3'
services:
  
  web:
    image: nginx:latest
    container_name: hvz_web
    depends_on:
      - api
    volumes:
      - ./config/web-server/production-nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/:/www/
    ports:
      - 80:80
      - 443:443

  api:
    build:
      context: ./config/api
      args:
        SPECIAL_REQUIREMENTS: "production-requirements.txt"

    container_name: hvz_api
    entrypoint: ["uwsgi", "--ini", "app.ini"]
    depends_on:
      - database
    volumes:
      - ./api/:/code/
    environment:
      DATABASE: hvz_production

  database:
    image: postgres:latest
    container_name: hvz_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: hvz_production
