"""add required amount

Revision ID: a0428a3744c0
Revises: 8a95dcef4be3
Create Date: 2020-05-31 17:43:39.929690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0428a3744c0'
down_revision = '8a95dcef4be3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('required_amount', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'required_amount')
    # ### end Alembic commands ###
